### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by matthias-da** [statistikat/simPop#6]
Does anybody see the problem? We receive a warning by checking the package:

```
 Codoc mismatches from documentation object 'simRelation':
  simRelation
    Code: function(simPopObj, relation = "relate", head = "head", direct
                   = NULL, additional, limit = NULL, censor = NULL, maxit
                   = 500, MaxNWts = 2000, eps = NULL, nr_cpus = NULL,
                   seed = 1, regModel = NULL, verbose = FALSE, method =
                   c("multinom", "ctree", "cforest", "ranger"), by =
                   "strata")
    Docs: function(simPopObj, relation = "relate", head = "head", direct
                   = NULL, additional = c("nation", "ethnic",
                   "religion"), limit = NULL, censor = NULL, maxit = 500,
                   MaxNWts = 2000, eps = NULL, nr_cpus = NULL, seed)
    Argument names in code not in docs:
      regModel verbose method by
    Mismatches in argument default values:
      Name: 'additional' Code:  Docs: c("nation", "ethnic", "religion")
      Name: 'seed' Code: 1 Docs: 
```

The warning says that Docs does not continue with parameter regModel (but it does), and nation ethnic etc is under dontrun only and should be therefore no problem at all...

**Comment by bernhard-da** [comment]
i have added an additional export (`stats::terms`) in https://github.com/statistikat/simPop/commit/d96675082bb761d4824111370b8335e752caa0cf and changed the documentation-format in `simRelation()` to markdown; but aside from that, I cannot reproduce the issue under 4.0.3 unfortunately. 

did you run devtools::document() prior to checking @matthias-da
