### ISSUE TITLE
simRelation implementation error ($ operator)

### ISSUE THREAD

**Issue by aastha-shah** [statistikat/simPop#8]
Hello, I just came across your library and I was trying to run a few examples. After a successful installation, I found that the `simRelation` example, as listed [here](https://rdrr.io/cran/simPop/man/simRelation.html) raises an `Error: $ operator is invalid for atomic vectors`, resulting in the relevant columns in `ghanaP@pop@data` being absent. Any insight would be helpful. Apologies if I'm going by the wrong version of the docs, I believe the man pages on this repo have the same code for this function.

**Comment by matthias-da** [comment]
Thank you for pointing this out. A quick and dirty solution (only tested for this case) is already implemented.

Please install the newest version 

```{r}
devtools::install_github("statistikat/simPop")
```

Best
Matthias

**Comment by aastha-shah** [comment]
Hi, unfortunately, I still get the same error despite having all other packages up to date. Could it be a R or RStudio issue?

**Comment by manab-prakash** [comment]
unfortunately, I still get the same error.

**Comment by matthias-da** [comment]
Originally this function was implemented by Andreas Alfons from Rotterdam (you may also contact him), and updated and rewritten by Bernhard. I assigned him to this issue. Best, Matthias

**Comment by bernhard-da** [comment]
hi @manab-prakash could you please try, if https://github.com/statistikat/simPop/commit/c711b8c142bcff34341f5e4413bcd3c74a586e31 fixes this? you can install the dev-branch with
```
remotes::install_github("statistikat/simPop", ref = "fix-issue-8")
```
and try the same example as reported.

**Comment by manab-prakash** [comment]
@bernhard-da  I tested it. It now works as expected. Thank you !!! and Cheers!!!

**Comment by bernhard-da** [comment]
hi, thx for confirming that the fix works; merged into master and will be in the next cran version;
